defaults:
  - _self_
  - task: base_dp

name: dp
_target_: workspace.dp_workspace.DPWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "debug"

horizon: 16
n_action_steps: 8
n_obs_steps: 2
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
policy:
  _target_: policy.dp_unet.DiffusionUnetPolicy
  shape_meta: ${shape_meta}
  diffusion_step_embed_dim: 64
  down_dims: [512, 1024, 2048]
  horizon: ${horizon}
  kernel_size: 5
  n_action_steps: ${n_action_steps}
  n_groups: 8
  n_obs_steps: ${n_obs_steps}
  cond_predict_scale: true
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small
    clip_sample: true
    prediction_type: epsilon
  num_inference_steps: 100
  obs_encoders:
    - _target_: model.vision.rgb_encoder.RobomimicRgbEncoder
      shape_meta: ${shape_meta}
      crop_shape: [212, 212]
      use_group_norm: true
      eval_fixed_crop: false
      share_rgb_model: false

ema:
  _target_: model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 32
  num_workers: 8
  shuffle: true
  pin_memory: true
  persistent_workers: false

val_dataloader:
  batch_size: 32
  num_workers: 8
  shuffle: false
  pin_memory: true
  persistent_workers: false

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: false
  resume: true
  cuda_kernel_tuning: true
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 1001
  gradient_accumulate_every: 1
  use_ema: true
  freeze_encoder: false
  rollout_every: 50
  checkpoint_every: 250
  val_every: 50
  sample_every: 50
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  project: modular_policy_debug
  resume: true
  mode: online
  name: ${now:%Y%m%d.%H%M%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  save_ckpt: true
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: "best-{epoch:04d}.ckpt"
  save_last_ckpt: true
  save_last_snapshot: false

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
